"""add_group_discount_and_refunds

Revision ID: 78337a48703c
Revises: ce24eafc92ca
Create Date: 2026-07-11 16:09:13.612550

"""
from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78337a48703c'
down_revision: Union[str, None] = 'ce24eafc92ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('group_discount_threshold', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('group_discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('events', sa.Column('allow_refunds', sa.Boolean(), server_default='1', nullable=False))
    # op.alter_column('orders', 'status',
    #            existing_type=sa.VARCHAR(length=9),
    #            type_=sa.Enum('pending', 'confirmed', 'cancelled', 'refunded', 'refund_pending', name='orderstatus'),
    #            existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('orders', 'status',
    #            existing_type=sa.Enum('pending', 'confirmed', 'cancelled', 'refunded', 'refund_pending', name='orderstatus'),
    #            type_=sa.VARCHAR(length=9),
    #            existing_nullable=False)
    op.drop_column('events', 'allow_refunds')
    op.drop_column('events', 'group_discount_percent')
    op.drop_column('events', 'group_discount_threshold')
    # ### end Alembic commands ###
