"""initial_schema

Revision ID: ce24eafc92ca
Revises: None
Create Date: 2026-07-11 15:41:16.339179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.models



# revision identifiers, used by Alembic.
revision: str = 'ce24eafc92ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_categories',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizers',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'active', 'suspended', name='organizerstatus'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizers_email'), 'organizers', ['email'], unique=True)
    op.create_table('platform_settings',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('events',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('organizer_id', app.models.models.GUID(), nullable=False),
    sa.Column('category_id', app.models.models.GUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policies', sa.Text(), nullable=True),
    sa.Column('banner_image_url', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('venue_name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('online_url', sa.String(length=500), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'published', 'cancelled', 'archived', name='eventstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('allow_transfers', sa.Boolean(), nullable=False),
    sa.Column('transfer_deadline_hours', sa.Integer(), nullable=True),
    sa.Column('max_transfers_per_ticket', sa.Integer(), nullable=True),
    sa.Column('allow_resale', sa.Boolean(), nullable=False),
    sa.Column('max_resale_markup_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('approved_by', app.models.models.GUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['event_categories.id'], ),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizer_payouts',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('organizer_id', app.models.models.GUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'processed', 'failed', name='payoutstatus'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promo_codes',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('event_id', app.models.models.GUID(), nullable=False),
    sa.Column('organizer_id', app.models.models.GUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('percentage', 'fixed', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('applicable_ticket_type_ids', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'code', name='uq_event_promo_code')
    )
    op.create_table('ticket_types',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('event_id', app.models.models.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('sales_start', sa.DateTime(), nullable=True),
    sa.Column('sales_end', sa.DateTime(), nullable=True),
    sa.Column('purchase_limit', sa.Integer(), nullable=False),
    sa.Column('min_purchase', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('event_id', app.models.models.GUID(), nullable=False),
    sa.Column('promo_code_id', app.models.models.GUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'refunded', name='orderstatus'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_guest_email'), 'orders', ['guest_email'], unique=False)
    op.create_table('order_items',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('order_id', app.models.models.GUID(), nullable=False),
    sa.Column('ticket_type_id', app.models.models.GUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['ticket_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('order_item_id', app.models.models.GUID(), nullable=False),
    sa.Column('ticket_code', sa.String(length=100), nullable=False),
    sa.Column('qr_image_url', sa.String(length=500), nullable=True),
    sa.Column('attendee_name', sa.String(length=255), nullable=True),
    sa.Column('attendee_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'used', 'transferred', 'resold', 'cancelled', name='ticketstatus'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_code')
    )
    op.create_table('resale_listings',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('ticket_id', app.models.models.GUID(), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_email', sa.String(length=255), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', 'removed', name='resalestatus'), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('buyer_ticket_id', app.models.models.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_transfers',
    sa.Column('id', app.models.models.GUID(), nullable=False),
    sa.Column('ticket_id', app.models.models.GUID(), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('to_name', sa.String(length=255), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_transfers')
    op.drop_table('resale_listings')
    op.drop_table('tickets')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_guest_email'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('ticket_types')
    op.drop_table('promo_codes')
    op.drop_table('organizer_payouts')
    op.drop_table('events')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_organizers_email'), table_name='organizers')
    op.drop_table('organizers')
    op.drop_table('event_categories')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
